Repository NodeBB/NodeBB, pull requests merged in 2020-09, with the labels that each got.

#8607 refactor: socket posts delete/restore/purge so tid is not necessary
  public/src/client/topic/delete-posts.js
  public/src/client/topic/postTools.js
  src/socket.io/posts/tools.js
  test/posts.js
Labels: tech debt

#8617 Remove sounds
  .eslintignore
  .gitignore
  public/openapi/read.yaml
  public/src/admin/settings.js
  public/src/admin/settings/sounds.js
  public/src/client/account/settings.js
  public/src/client/chats/messages.js
  public/src/modules/notifications.js
  public/src/modules/sounds.js
  src/cli/index.js
  src/controllers/accounts/settings.js
  src/controllers/admin/settings.js
  src/controllers/admin/uploads.js
  src/emailer.js
  src/install.js
  src/meta/build.js
  src/meta/index.js
  src/meta/sounds.js
  src/plugins/data.js
  src/plugins/index.js
  src/plugins/load.js
  src/routes/admin.js
  src/socket.io/modules.js
  src/upgrades/1.15.0/disable_sounds_plugin.js
  src/user/settings.js
  src/views/admin/partials/menu.tpl
  src/views/admin/settings/sounds.tpl
  src/webserver.js
  test/build.js
  test/controllers-admin.js
  test/meta.js
  test/mocks/databasemock.js
  test/socket.io.js
  test/uploads.js
  test/user.js
Labels: breaking change (plugins)

#8641 feat: fullname search
  src/controllers/admin/users.js
  src/database/postgres/sorted.js
  src/upgrades/1.15.0/fullname_search_set.js
  src/user/create.js
  src/user/delete.js
  src/user/profile.js
  src/user/search.js
  test/user.js
Labels: enhancement
