Repository NodeBB/NodeBB, pull requests merged in 2020-02, with the labels that each got.

#8148 fix: #8142, broken site if no server-side session
  public/src/client/login.js
  src/meta/configs.js
  src/middleware/headers.js
  src/webserver.js
  test/helpers/index.js
Labels: bug, enhancement

#8169 fix: #8168 re-allowing slashes in homePageRoute
  src/user/settings.js
Labels: bug, regression

#8170 feat: settings sorted list
  public/src/modules/settings.js
  public/src/modules/settings/sorted-list.js
  src/meta/settings.js
  test/meta.js
Labels: enhancement
