Repository NodeBB/NodeBB, pull requests merged in 2020-10, with the labels that each got.

#8710 feat: category filter on post queue
  public/openapi/api/post-queue.yaml
  public/src/client/post-queue.js
  public/src/modules/categoryFilter.js
  public/src/modules/topicList.js
  src/controllers/helpers.js
  src/controllers/mods.js
Labels: breaking change (themes)

#8731 feat: revoke user sessions above threshold
  install/data/defaults.json
  public/language/en-GB/admin/settings/cookies.json
  src/user/auth.js
  src/views/admin/settings/cookies.tpl
Labels: enhancement

#8762 Admin/users
  public/language/en-GB/admin/manage/users.json
  public/openapi/read.yaml
  public/openapi/read/admin/manage/privileges/cid.yaml
  public/openapi/read/admin/manage/users.yaml
  public/openapi/read/admin/manage/users/banned.yaml
  public/openapi/read/admin/manage/users/flagged.yaml
  public/openapi/read/admin/manage/users/inactive.yaml
  public/openapi/read/admin/manage/users/latest.yaml
  public/openapi/read/admin/manage/users/most-reputation.yaml
  public/openapi/read/admin/manage/users/no-posts.yaml
  public/openapi/read/admin/manage/users/not-validated.yaml
  public/openapi/read/admin/manage/users/search.yaml
  public/openapi/read/admin/manage/users/top-posters.yaml
  public/src/admin/manage/users.js
  public/src/client/topic/change-owner.js
  public/src/client/users.js
  src/controllers/admin/groups.js
  src/controllers/admin/users.js
  src/controllers/users.js
  src/controllers/write/groups.js
  src/groups/create.js
  src/groups/index.js
  src/groups/join.js
  src/messaging/edit.js
  src/messaging/index.js
  src/privileges/admin.js
  src/privileges/helpers.js
  src/routes/admin.js
  src/socket.io/admin/user.js
  src/socket.io/groups.js
  src/socket.io/user/search.js
  src/upgrade.js
  src/upgrades/1.15.0/verified_users_group.js
  src/user/create.js
  src/user/delete.js
  src/user/email.js
  src/user/posts.js
  src/user/profile.js
  src/user/reset.js
  src/user/search.js
  src/views/admin/manage/users.tpl
  src/views/admin/partials/create_user_modal.tpl
  test/controllers-admin.js
  test/controllers.js
  test/groups.js
  test/socket.io.js
  test/user.js
Labels: breaking change (plugins)

#8702 Update bundled logos with new branding
  README.md
  public/favicon.ico
  public/images/logo.png
  public/images/logo.svg
  public/images/logo@3x.png
  public/images/touch/144.png
  public/images/touch/192.png
  public/images/touch/36.png
  public/images/touch/48.png
  public/images/touch/512.png
  public/images/touch/72.png
  public/images/touch/96.png
  public/logo.png
  src/meta/tags.js
  src/middleware/index.js
Labels: enhancement
