Repository NodeBB/NodeBB, pull requests merged in 2020-06, with the labels that each got.

#8364 Making render(admin)?(header|footer) awaitable
  src/middleware/admin.js
  src/middleware/header.js
  src/middleware/render.js
Labels: enhancement, tech debt

#8346 #8344
  src/analytics.js
  src/middleware/admin.js
  src/middleware/header.js
  src/middleware/headers.js
  src/middleware/helpers.js
  src/middleware/index.js
  src/middleware/maintenance.js
  src/middleware/user.js
  src/routes/authentication.js
Labels: enhancement

#8355 Privileges for Admin Control Panel
  public/language/en-GB/admin/manage/privileges.json
  public/openapi/read.yaml
  public/src/admin/manage/privileges.js
  public/src/admin/modules/search.js
  public/src/modules/helpers.js
  src/controllers/admin.js
  src/controllers/admin/dashboard.js
  src/controllers/admin/privileges.js
  src/middleware/admin.js
  src/privileges/admin.js
  src/privileges/categories.js
  src/privileges/global.js
  src/privileges/index.js
  src/routes/admin.js
  src/routes/index.js
  src/socket.io/admin.js
  src/socket.io/admin/categories.js
  src/views/admin/dashboard.tpl
  src/views/admin/manage/privileges.tpl
  src/views/admin/partials/menu.tpl
  src/views/admin/partials/privileges/category.tpl
  src/views/admin/partials/privileges/global.tpl
  src/views/admin/partials/quick_actions/buttons.tpl
Labels: breaking change (plugins), breaking change (themes), enhancement

#8413 Topic hooks extension
  src/topics/data.js
Labels: enhancement
