Repository NodeBB/NodeBB, pull requests merged in 2020-05, with the labels that each got.

#8324 Remove allowFileUploads ACP option
  install/data/defaults.json
  public/openapi/read.yaml
  src/controllers/api.js
  src/controllers/uploads.js
  src/upgrade.js
  src/upgrades/1.13.0/clean_flag_byCid.js
  src/upgrades/1.13.0/clean_post_topic_hash.js
  src/upgrades/1.13.0/cleanup_old_notifications.js
  src/upgrades/1.13.3/fix_users_sorted_sets.js
  src/upgrades/1.13.4/remove_allowFileUploads_priv.js
  src/upgrades/TEMPLATE
  src/views/admin/settings/uploads.tpl
  test/uploads.js
Labels: enhancement, tech debt

#8336 feat: add privilege give/rescind hooks
  src/categories/create.js
  src/cli/reset.js
  src/install.js
  src/privileges/categories.js
  src/privileges/global.js
  src/privileges/helpers.js
  src/socket.io/admin/categories.js
  src/upgrades/1.10.0/post_history_privilege.js
  src/upgrades/1.10.0/search_privileges.js
  src/upgrades/1.10.2/local_login_privileges.js
  src/upgrades/1.12.0/global_view_privileges.js
  src/upgrades/1.12.0/group_create_privilege.js
  src/upgrades/1.12.3/give_mod_info_privilege.js
  src/upgrades/1.12.3/give_mod_privileges.js
  src/upgrades/1.13.4/remove_allowFileUploads_priv.js
  src/upgrades/1.5.2/tags_privilege.js
  src/upgrades/1.7.4/global_upload_privilege.js
  src/upgrades/1.7.4/vote_privilege.js
  src/upgrades/1.8.0/give_signature_privileges.js
  src/upgrades/1.8.0/give_spiders_privileges.js
  test/authentication.js
  test/controllers.js
  test/feeds.js
  test/flags.js
  test/groups.js
  test/mocks/databasemock.js
  test/posts.js
  test/search.js
  test/topics.js
  test/uploads.js
Labels: breaking change (plugins)

#8338 feat: fix session mismatch errors by clearing cookie on logout
  public/src/admin/admin.js
  public/src/app.js
  public/src/client/login.js
  src/controllers/api.js
  src/controllers/authentication.js
  src/middleware/header.js
  src/middleware/headers.js
  src/routes/authentication.js
  src/webserver.js
Labels: enhancement
