Repository NodeBB/NodeBB, pull requests merged in 2021-08, with the labels that each got.

#9688 Remove some deprecated/unnecessary code
  src/meta/js.js
  src/middleware/header.js
  src/middleware/user.js
  src/routes/user.js
Labels: breaking change (plugins)

#9733 Server-side rendering of topic events
  public/src/client/topic/posts.js
  public/src/modules/helpers.js
Labels: breaking change (themes)

#9699 feat: column based view on wide priv. tables
  public/language/en-GB/admin/manage/privileges.json
  public/src/admin/manage/privileges.js
  public/src/admin/modules/checkboxRowSelector.js
  public/src/modules/categorySelector.js
  src/categories/create.js
  src/socket.io/admin/categories.js
  src/views/admin/partials/categories/select-category.tpl
  src/views/admin/partials/privileges/category.tpl
Labels: enhancement
